version: "3"

services:
  prod-api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: project-api
    environment:
      API_PORT: $API_PORT
      POSTGRES_DB: $DB_NAME
      DB_ADMIN_USER: $DB_ADMIN_USER
      DB_ADMIN_PASS: $DB_ADMIN_PASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_READONLY_USER: $DB_READONLY_USER
      DB_READONLY_PASS: $DB_READONLY_PASS
      DB_WRITE_USER: $DB_WRITE_USER
      DB_WRITE_PASS: $DB_WRITE_PASS
      DB_DEFAULT_SCHEMA: $DB_DEFAULT_SCHEMA
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      WEB_HOST: $WEB_HOST
    volumes:
      - /usr/src/api/node_modules # Saves the node modules so it does not have to re-install
      - ./api:/usr/src/api # Mounts the host folder(s) onto the docker container for live development
    ports:
      - "$API_PORT:$API_PORT"
    env_file:
      - .env
